export const wordData = {
    "verbs": [
    {"kanji":"行<rt>い<\/rt>く","type":"irv","eng":"gå"},
    {"kanji":"する","type":"irv","eng":"göra"},
    {"kanji":"来<rt>く<\/rt>る","type":"irv","eng":"komma"},
    {"kanji":"ある","type":"irv","eng":"ha, finns, är (oanimat)"},
    {"kanji":"いる","type":"ru","eng":"finns, är (levande varelser)"},
    {"kanji":"食<rt>た<\/rt>べる","type":"ru","eng":"äta"},
    {"kanji":"起<rt>お<\/rt>きる","type":"ru","eng":"stiga upp, vakna"},
    {"kanji":"あげる","type":"ru","eng":"ge"},
    {"kanji":"見<rt>み<\/rt>る","type":"ru","eng":"se, titta"},
    {"kanji":"開<rt>あ<\/rt>ける","type":"ru","eng":"öppna"},
    {"kanji":"寝<rt>ね<\/rt>る","type":"ru","eng":"sova, gå till sängs"},
    {"kanji":"上<rt>あ<\/rt>がる","type":"ru","eng":"gå upp, stiga"},
    {"kanji":"帰<rt>かえ<\/rt>る","type":"ru","eng":"återvända, gå hem"},
    {"kanji":"買<rt>か<\/rt>う","type":"u","eng":"köpa"},
    {"kanji":"会<rt>あ<\/rt>う","type":"u","eng":"träffas"},
    {"kanji":"言<rt>い<\/rt>う","type":"u","eng":"säga, uttala"},
    {"kanji":"使<rt>つか<\/rt>う","type":"u","eng":"använda"},
    {"kanji":"待<rt>ま<\/rt>つ","type":"u","eng":"vänta"},
    {"kanji":"聞<rt>き<\/rt>く","type":"u","eng":"höra, lyssna"},
    {"kanji":"聞<rt>く<\/rt>く","type":"u","eng":"fråga"},
    {"kanji":"働<rt>はたら<\/rt>く","type":"u","eng":"arbeta"},
    {"kanji":"死<rt>し<\/rt>ぬ","type":"u","eng":"dö, avlida"},
    {"kanji":"飲<rt>の<\/rt>む","type":"u","eng":"dricka"},
    {"kanji":"読<rt>よ<\/rt>む","type":"u","eng":"läsa"},
    {"kanji":"遊<rt>あそ<\/rt>ぶ","type":"u","eng":"leka, ha kul"},
    {"kanji":"話<rt>はな<\/rt>す","type":"u","eng":"prata, tala"},
    {"kanji":"泳<rt>およ<\/rt>ぐ","type":"u","eng":"simma"},
    {"kanji":"分<rt>わ<\/rt>かる","type":"u","eng":"förstå"},
    {"kanji":"勉<rt>べん<\/rt>強<rt>きょう<\/rt>する","type":"irv","eng":"studera"},
    {"kanji":"借<rt>か<\/rt>りる","type":"ru","eng":"låna, hyra"},
    {"kanji":"乗<rt>の<\/rt>る","type":"u","eng":"kliva på, åka"},
    {"kanji":"座<rt>すわ<\/rt>る","type":"u","eng":"sitta"},
    {"kanji":"撮<rt>と<\/rt>る","type":"u","eng":"ta en bild"},
    {"kanji":"出<rt>で<\/rt>かける","type":"ru","eng":"gå ut"},
    {"kanji":"教<rt>おし<\/rt>える","type":"ru","eng":"undervisa, berätta"},
    {"kanji":"電<rt>で<\/rt>話<rt>わ<\/rt>する","type":"irv","eng":"ringa"},
    {"kanji":"掃<rt>そう<\/rt>除<rt>じ<\/rtする","type":"irv","eng":"städa"},
    {"kanji":"持<rt>も<\/rt>ってくる","type":"irv","eng":"ta med (objekt)"},
    {"kanji":"連<rt>つ<\/rt>れてくる","type":"irv","eng":"ta med (person)"}
    ],
    "adjectives": [
        {"kanji":"いい","type":"ira","eng":"good"},
        {"kanji":"かっこいい","type":"ira","eng":"cool, handsome"},
        {"kanji":"赤<rt>あか<\/rt>い","type":"i","eng":"red"},
        {"kanji":"新<rt>あたら<\/rt>しい","type":"i","eng":"new"},
        {"kanji":"暑<rt>あつ<\/rt>い","type":"i","eng":"hot (weather)"},
        {"kanji":"危<rt>あぶ<\/rt>ない","type":"i","eng":"dangerous"},
        {"kanji":"美<rt>お<\/rt>味<rt>い<\/rt>しい","type":"i","eng":"delicious"},
        {"kanji":"大<rt>おお<\/rt>きい","type":"i","eng":"big"},
        {"kanji":"遅<rt>おそ<\/rt>い","type":"i","eng":"late, slow"},
        {"kanji":"面<rt>おも<\/rt>白<rt>しろ<\/rt>い","type":"i","eng":"interesting, funny"},
        {"kanji":"可<rt>か<\/rt>愛<rt>わい<\/rt>い","type":"i","eng":"cute, pretty"},
        {"kanji":"寒<rt>さむ<\/rt>い","type":"i","eng":"cold (weather)"},
        {"kanji":"高<rt>たか<\/rt>い","type":"i","eng":"high, expensive"},
        {"kanji":"楽<rt>たの<\/rt>しい","type":"i","eng":"fun, pleasant"},
        {"kanji":"小<rt>ちい<\/rt>さい","type":"i","eng":"small"},
        {"kanji":"詰<rt>つま<\/rt>らない","type":"i","eng":"uninteresting, boring","altOkurigana":["詰まらない"]},
        {"kanji":"速<rt>はや<\/rt>い","type":"i","eng":"fast, quick"},
        {"kanji":"古<rt>ふる<\/rt>い","type":"i","eng":"old (thing)"},
        {"kanji":"欲<rt>ほ<\/rt>しい","type":"i","eng":"wanted, desired"},
        {"kanji":"難<rt>むずか<\/rt>しい","type":"i","eng":"difficult"},
        {"kanji":"安<rt>やす<\/rt>い","type":"i","eng":"cheap"},
        {"kanji":"好<rt>す<\/rt>き","type":"na","eng":"like"},
        {"kanji":"有<rt>ゆう<\/rt>名<rt>めい<\/rt>","type":"na","eng":"famous"},
        {"kanji":"きれい","type":"na","eng":"beautiful, tidy"},
        {"kanji":"嫌<rt>きら<\/rt>い","type":"na","eng":"dislike"},
        {"kanji":"静<rt>しず<\/rt>か","type":"na","eng":"quiet"},
        {"kanji":"元<rt>げん<\/rt>気<rt>き<\/rt>","type":"na","eng":"healthy"},
        {"kanji":"色<rt>いろ<\/rt>々<rt>いろ<\/rt>","type":"na","eng":"various"},
        {"kanji":"心<rt>しん<\/rt>配<rt>ぱい<\/rt>","type":"na","eng":"worry, care"},
        {"kanji":"嫌<rt>いや<\/rt>","type":"na","eng":"unpleasant, detestable"},
        {"kanji":"十<rt>じゅう<\/rt>分<rt>ぶん<\/rt>","type":"na","eng":"sufficient"},
        {"kanji":"立<rt>りっ<\/rt>派<rt>ぱ<\/rt>","type":"na","eng":"excellent, splendid"},
        {"kanji":"同<rt>おな<\/rt>じ","type":"na","eng":"same, alike"},
        {"kanji":"大<rt>だい<\/rt>丈<rt>じょう<\/rt>夫<rt>ぶ<\/rt>","type":"na","eng":"okay, safe"},
        {"kanji":"真<rt>ま<\/rt>っ<ruby>直<rt>す<\/rt><\/ruby>ぐ","type":"na","eng":"straight, direct","altOkurigana":["真直ぐ","真すぐ","真っすぐ"]},
        {"kanji":"下<rt>へ<\/rt>手<rt>た<\/rt>","type":"na","eng":"unskilled"},
        {"kanji":"簡<rt>かん<\/rt>単<rt>たん<\/rt>","type":"na","eng":"simple, easy"},
        {"kanji":"楽<rt>らく<\/rt>","type":"na","eng":"comfortable, easy"},
        {"kanji":"残<rt>ざん<\/rt>念<rt>ねん<\/rt>","type":"na","eng":"unfortunate, disappointing"},
        {"kanji":"必<rt>ひつ<\/rt>要<rt>よう<\/rt>","type":"na","eng":"necessary"}
    ]
}